In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import cross_val_score
from sklearn import metrics
from sklearn.svm import LinearSVC
import matplotlib.pyplot as plt
import numpy as np
np.random.seed(42)

In [3]:
df=pd.read_csv("/content/training data.csv")
df

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
...        ...       ...       ...       ...       ...       ...        ...   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859   1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193   0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936   1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435   1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756   1.705029   

             kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0      274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1      634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2     1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3        4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4        4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   
...           ...       ...       ...  ...       ...       ...       ...   
3163     6.630383  0.962934  0.763182  ...  0.131884  0.182790  0.083770   
3164     2.503954  0.960716  0.709570  ...  0.116221  0.188980  0.034409   
3165     6.604509  0.946854  0.654196  ...  0.142056  0.209918  0.039506   
3166     5.388298  0.950436  0.675470  ...  0.143659  0.172375  0.034483   
3167     5.769115  0.938829  0.601529  ...  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx   label  
0     0.275862  0.007812  0.007812  0.007812  0.000000  0.000000    male  
1     0.250000  0.009014  0.007812  0.054688  0.046875  0.052632    male  
2     0.271186  0.007990  0.007812  0.015625  0.007812  0.046512    male  
3     0.250000  0.201497  0.007812  0.562500  0.554688  0.247119    male  
4     0.266667  0.712812  0.007812  5.484375  5.476562  0.208274    male  
...        ...       ...       ...       ...       ...       ...     ...  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929  female  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897  female  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759  female  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002  female  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000  female  

[3168 rows x 21 columns]

In [18]:
X = df[['meanfun' , 'minfun', 'maxfun']].values
y_ = df['label'].values

In [19]:
X_train, X_test, y_train, y_test=train_test_split(X,y_,test_size=0.12)

In [20]:
model=LinearSVC()
model.fit(X_train,y_train)
train_pred=model.predict(X_train)
y_preds=model.predict(X_test)

print(f"Training score = {metrics.accuracy_score(y_train,train_pred)}")
print(f"Testing score = {metrics.accuracy_score(y_test,y_preds)}")


Training score = 0.9573017581628992
Testing score = 0.958005249343832


In [21]:
model.coef_

array([[-25.41047146,   3.30427954,   1.62705527]])

In [22]:
model.intercept_

array([3.08062536])

In [23]:
np.random.seed(42)
z=df["label"]
y=z.copy()
y.loc[(y=="female")]=-1
y.loc[(y=="male")]=1
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.12)

X_train = np.hstack((X_train,np.ones((X_train.shape[0],1))))
y_train =y_train

In [24]:
y_train.values

array([-1, -1, 1, ..., 1, 1, 1], dtype=object)

In [33]:
from tqdm import tqdm

w = np.zeros((4,1))


alpha = 10/X_train.shape[0]  # lr/m
epochs=10000
C=1
for i in tqdm(range(1,epochs)):
    for j in range(X_train.shape[0]):
        if y_train.iloc[j]*(X_train[j]@w)<=1:
            w=w-alpha*w/i
            w=w-alpha*C*((-y_train.iloc[j]*X_train[j])[:,np.newaxis])
        else:
            w=w-alpha*w/i
            
y_pred=X_train@w
y_pred=np.where(y_pred > 0, 1, y_pred)
y_pred=np.where(y_pred < 0, -1, y_pred)
np.mean(y_pred==y_train[:,np.newaxis])

100%|██████████| 9999/9999 [11:00<00:00, 15.14it/s]
<ipython-input-33-eb553c3fa70b>:20: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.mean(y_pred==y_train[:,np.newaxis])


0.9562253318980983

In [32]:
X_test2=np.hstack((X_test,np.ones((X_test.shape[0],1))))
y_pred=X_test2@w
y_pred=np.where(y_pred > 0, 1, y_pred)
y_pred=np.where(y_pred < 0, -1, y_pred)
np.mean(y_pred==y_test[:,np.newaxis])

<ipython-input-32-b6c822858261>:5: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.mean(y_pred==y_test[:,np.newaxis])


0.9553805774278216